proxy_admin_url: http://admin.dasfilter.com
proxy_web_url: http://www.dasfilter.com
proxy_static_url: http://static.dasfilter.com

domain: dasfilter.com
domain_redirects: .das-filter.com .das-filter.de .das-filter.net .das-filter.org .dasfilter.de .dasfilter.net .dasfilter.org
