proxy_admin_url: http://admin.staging.dasfilter.com
proxy_web_url: http://www.staging.dasfilter.com
proxy_static_url: http://static.staging.dasfilter.com

domain: staging.dasfilter.com
domain_redirects: ""
