- hosts: api
  remote_user: deploy
  vars:
    app_repo: git@bitbucket.org:skoni/df-api-server.git
    app_dir: "{{ deploy_home }}/app"
    app_env_vars:
      NODE_ENV: "{{ node_env }}"

      DF_API_PORT: 8060
      DF_STATIC_PORT: 8050

      DF_DB_URL: "{{ db_url }}"
      DF_DB_USER: "{{ db_user }}"
      DF_DB_PASS: "{{ db_pass }}"

      DF_WEB_URL: "{{ proxy_web_url }}"
      DF_ADMIN_URL: "{{ proxy_admin_url }}"
      DF_STATIC_URL: "{{ proxy_static_url }}"
      DF_API_URL: "http://{{ groups['api'][0] }}:8060"

      DF_API_KEY: "{{ api_key }}"
      DF_COOKIE_PASS: "{{ cookie_pass }}"

  roles:
    # - debug
    - app_deploy
