version: '3.1'
services:
  nginx:
    image: nginx:1.13
    volumes:
      - './config/nginx.conf:/etc/nginx/nginx.conf'
    ports:
      - '80:80'

  couchdb:
    image: "ntr-couch"
    ports:
      - "5984:5984"
    environment:
      NODENAME: dasfilter
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: secret
    volumes:
      - './data/couchdb/:/couchdb/data/'
      - './data/clouseau/:/clouseau/target/clouseau1/'

  # Use as aws s3 replacement in local development
  # s3:
  #   image: lphoward/fake-s3
  #   ports:
  #     - "4569:4569"

  app:
    build:
      context: .
    volumes:
      - ./plugins:/opt/app/plugins
      - ./index.js:/opt/app/index.js
      - ./manifest.js:/opt/app/manifest.js
      - ./gulpfile.js:/opt/app/gulpfile.js
      - ./entrypoint.sh:/opt/app/entrypoint.sh
      - ./start-dev.sh:/opt/app/start-dev.sh
    ports:
      - '8080:8080'
    command: start_prod
