- hosts: admin
  remote_user: deploy
  vars:
    app_repo: git@bitbucket.org:skoni/df-admin-server.git
    app_dir: "{{ deploy_home }}/app"

    firewall_open_ports:
      - 8070
      
    env_vars:
      NODE_ENV: "{{ node_env }}"

      DF_WEB_URL: "{{ proxy_web_url }}"
      DF_ADMIN_URL: "{{ proxy_admin_url }}"
      DF_STATIC_URL: "{{ proxy_static_url }}"
      DF_API_URL: "http://{{ groups['api'][0] }}:8050"

      DF_APP_KEY: "{{ app_key }}"
      DF_APP_SECRET: "{{ app_secret }}"
      
      DF_COOKIE_PASS: "{{ cookie_pass }}"

  roles:
    - env
    - nodejs
    - app_provision
    - firewall
    
