- hosts: web
  remote_user: deploy
  vars:
    app_repo: git@bitbucket.org:skoni/df-web-server.git
    app_dir: "{{ deploy_home }}/app"
    app_open_ports:
      - 8080

  roles:
    # - debug
    - nodejs
    - app_provision
