- name: Install packages required for htpasswd
  sudo: yes
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
    - python-passlib
  
- name: Create htpasswd
  sudo: yes
  htpasswd: path=/etc/nginx/htpasswd name={{ app_key }} password={{ app_secret }}
  notify: Restart nginx

- name: Copy nginx sites
  sudo: yes
  template: src={{ item }} dest=/etc/nginx/sites-available
  with_items: proxy_sites
  notify: Restart nginx

- name: Link nginx sites
  sudo: yes
  shell: ln -s -f /etc/nginx/sites-available/{{ item }} /etc/nginx/sites-enabled/{{ item }}
  with_items: proxy_sites
  notify: Restart nginx
