- name: Copy nginx sites
  sudo: yes
  template: src={{ item }} dest=/etc/nginx/sites-available
  with_items:
    - admin-site
    - web-site
    - static-site

- name: Link nginx sites
  sudo: yes
  shell: ln -s -f /etc/nginx/sites-available/{{ item }} /etc/nginx/sites-enabled/{{ item }}
  with_items:
    - web-site
    - admin-site
    - static-site
  notify: Restart nginx
