
# install prequisites for couchdb
    
- name: Add Erlang Solutions apt repository
  sudo: yes
  apt_repository: repo='deb http://packages.erlang-solutions.com/ubuntu trusty contrib' state=present

- name: Add Erlang Solutions apt key
  sudo: yes
  apt_key: url=http://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc state=present

- name: Install packages required for building couchdb
  sudo: yes
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
    - git
    - build-essential
    - automake
    - autoconf
    - autoconf-archive
    - libtool
    - libicu-dev
    - libmozjs185-dev    
    - libcurl4-openssl-dev
    - pkg-config
    - erlang
    - python-pycurl    

# clone, build and install couchdb

- name: Clone couchdb repo
  git: repo=https://github.com/apache/couchdb.git version=1.6.0 dest=/home/deploy/couchdb
  
- name: Bootstrap couchdb
  command: ./bootstrap chdir=/home/deploy/couchdb

- name: Configure couchdb
  command: ./configure --disable-docs chdir=/home/deploy/couchdb

- name: Make and install couchdb
  sudo: yes
  command: make all install chdir=/home/deploy/couchdb

# user

- name: Create couchdb user
  sudo: yes
  user: name=couchdb system=yes shell=/bin/bash createhome=no home=/usr/local/var/lib/couchdb
  
- name: Move ownership of couchdb dirs to couchdb user
  sudo: yes
  shell: chown -R couchdb:couchdb {{ item }}
  with_items:
    - /usr/local/etc/couchdb
    - /usr/local/var/lib/couchdb
    - /usr/local/var/log/couchdb
    - /usr/local/var/run/couchdb
      
# configuration and service

- name: Copy couchdb local ini file
  sudo: yes
  template: src=couchdb_local.ini dest=/usr/local/etc/couchdb/local.ini owner=couchdb group=couchdb

- name: Link couchdb init.d script
  sudo: yes
  file: src=/usr/local/etc/init.d/couchdb path=/etc/init.d/couchdb state=link
  notify:
    - Restart couchdb
