

- name: Add apt key
  sudo: yes
  apt_key: url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present
    
- name: Add apt repository
  sudo: yes
  apt_repository: repo='deb http://packages.elasticsearch.org/elasticsearch/1.3/debian stable main' state=present

- name: Install elasticsearch and required packages
  sudo: yes
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
    - openjdk-7-jdk
    - elasticsearch

- name: Copy ini file
  sudo: yes
  template: src=elasticsearch.yml dest=/etc/elasticsearch/elasticsearch.yml owner=elasticsearch group=elasticsearch
  notify:
    - Restart elasticsearch
    
